"""
Application-wide constants for Lead Hunter Toolkit
Centralizes magic numbers and configuration defaults
"""

# Crawl and fetch limits
DEFAULT_MAX_SITES = 25
MIN_MAX_SITES = 1
MAX_MAX_SITES = 200

DEFAULT_MAX_PAGES = 5
MIN_MAX_PAGES = 1
MAX_MAX_PAGES = 20

DEFAULT_FETCH_TIMEOUT = 15
MIN_FETCH_TIMEOUT = 5
MAX_FETCH_TIMEOUT = 60

DEFAULT_CONCURRENCY = 8
MIN_CONCURRENCY = 1
MAX_CONCURRENCY = 32

# Search and places
DEFAULT_RADIUS_KM = 50
MIN_RADIUS_KM = 0
MAX_RADIUS_KM = 500

DEFAULT_MAX_PLACES = 20
MIN_MAX_PLACES = 1
MAX_MAX_PLACES = 100

# Scoring thresholds
MIN_SCORE = 0.0
MAX_SCORE = 10.0
DEFAULT_MIN_QUALITY = 0.0
DEFAULT_MIN_FIT = 0.0
DEFAULT_MIN_PRIORITY = 0.0

# LLM settings
DEFAULT_LLM_TEMPERATURE = 0.2
MIN_LLM_TEMPERATURE = 0.0
MAX_LLM_TEMPERATURE = 2.0

DEFAULT_LLM_TOP_K = 40
MIN_LLM_TOP_K = 1
MAX_LLM_TOP_K = 100

DEFAULT_LLM_TOP_P = 0.9
MIN_LLM_TOP_P = 0.0
MAX_LLM_TOP_P = 1.0

DEFAULT_LLM_MAX_TOKENS = 2048
MIN_LLM_MAX_TOKENS = 256
MAX_LLM_MAX_TOKENS = 8192

# Search scraper
DEFAULT_NUM_SOURCES = 5
MIN_NUM_SOURCES = 3
MAX_NUM_SOURCES = 20

# Dossier
DEFAULT_DOSSIER_NUM_PAGES = 2
MIN_DOSSIER_NUM_PAGES = 1
MAX_DOSSIER_NUM_PAGES = 10

# Onboarding/audit
DEFAULT_ONBOARD_CRAWL_PAGES = 10
MIN_ONBOARD_CRAWL_PAGES = 5
MAX_ONBOARD_CRAWL_PAGES = 50

DEFAULT_ONBOARD_AUDIT_PAGES = 3
MIN_ONBOARD_AUDIT_PAGES = 1
MAX_ONBOARD_AUDIT_PAGES = 10

DEFAULT_DOSSIER_CRAWL_PAGES = 5
MIN_DOSSIER_CRAWL_PAGES = 1
MAX_DOSSIER_CRAWL_PAGES = 20

# SERP tracking
DEFAULT_SERP_RESULTS = 20
MIN_SERP_RESULTS = 10
MAX_SERP_RESULTS = 50

# Site extraction
DEFAULT_SITEMAP_PAGES = 50
MIN_SITEMAP_PAGES = 1
MAX_SITEMAP_PAGES = 1000

DEFAULT_SITE_CRAWL_PAGES = 50
MIN_SITE_CRAWL_PAGES = 1
MAX_SITE_CRAWL_PAGES = 200

# HTTP timeouts
DEFAULT_HTTP_TIMEOUT = 15
AUDIT_HTTP_TIMEOUT = 15

# Directory paths
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PRESETS_DIR = os.path.join(BASE_DIR, "presets")

# User agent
USER_AGENT = "LeadHunter/1.0"
